# Generated by Django 6.0.1 on 2026-01-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
