# Generated by Django 6.0 on 2026-01-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email_verification_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
